//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Movies = new HashSet<Movy>();
            this.Users = new HashSet<User>();
        }
    
        public int actorID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int actorAge { get; set; }
        public byte[] actor_photo { get; set; }
        public string info { get; set; }
    
        public virtual ICollection<Movy> Movies { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
