//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActsIn
    {
        public string data { get; set; }
        public int actorID { get; set; }
        public string movieName { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
