//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Movies = new HashSet<Movy>();
            this.Users = new HashSet<User>();
        }
    
        public int directorID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int directorAge { get; set; }
        public string info { get; set; }
        public byte[] director_photo { get; set; }
    
        public virtual ICollection<Movy> Movies { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
