//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMDb_dataEntities : DbContext
    {
        public IMDb_dataEntities()
            : base("name=IMDb_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<ActsIn> ActsIn { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<user_comment> user_comment { get; set; }
        public virtual DbSet<User_fv_Actors> User_fv_Actors { get; set; }
        public virtual DbSet<User_fv_directors> User_fv_directors { get; set; }
        public virtual DbSet<User_fv_Movies> User_fv_Movies { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
