//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.user_comment = new HashSet<user_comment>();
            this.Actors = new HashSet<Actors>();
            this.Users = new HashSet<Users>();
        }
    
        public Nullable<int> directorID { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string paragraph { get; set; }
        public byte[] movies_photo { get; set; }
    
        public virtual Directors Directors { get; set; }
        public virtual ICollection<user_comment> user_comment { get; set; }
        public virtual ICollection<Actors> Actors { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
