//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public Movy()
        {
            this.user_comment = new HashSet<user_comment>();
            this.Actors = new HashSet<Actor>();
            this.Users = new HashSet<User>();
        }
    
        public Nullable<int> directorID { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string paragraph { get; set; }
        public byte[] movies_photo { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual ICollection<user_comment> user_comment { get; set; }
        public virtual ICollection<Actor> Actors { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
