//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_fv_directors
    {
        public string data { get; set; }
        public int userID { get; set; }
        public int directorID { get; set; }
    
        public virtual Directors Directors { get; set; }
        public virtual Users Users { get; set; }
    }
}
