//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.user_comment = new HashSet<user_comment>();
            this.Actors = new HashSet<Actors>();
            this.Directors = new HashSet<Directors>();
            this.Movies = new HashSet<Movies>();
        }
    
        public int ID { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public byte[] user_photo { get; set; }
    
        public virtual ICollection<user_comment> user_comment { get; set; }
        public virtual ICollection<Actors> Actors { get; set; }
        public virtual ICollection<Directors> Directors { get; set; }
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
