//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.user_comment = new HashSet<user_comment>();
            this.Actors = new HashSet<Actor>();
            this.Directors = new HashSet<Director>();
            this.Movies = new HashSet<Movy>();
        }
    
        public int ID { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public byte[] user_photo { get; set; }
    
        public virtual ICollection<user_comment> user_comment { get; set; }
        public virtual ICollection<Actor> Actors { get; set; }
        public virtual ICollection<Director> Directors { get; set; }
        public virtual ICollection<Movy> Movies { get; set; }
    }
}
